# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stuff and tings
email: me@richcunningham.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm supposed to write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rich0dify.github.io" # the base hostname & protocol for your site
twitter_username: rich0dify 
github_username:  rich0dify

# Build settings
markdown: kramdown

theme: jekyll-theme-slate